[storage]
db_driver = "postgres"
pg_username = "postgres"
pg_password = "postgres"
pg_host = "localhost"
pg_port = 5432
pg_db_name = "notification"
pg_params = "sslmode=disable"
log_sql_queries = true

[logging]
debug = true
log_level = ""

[kafka_broker]
address = "localhost:9092"
topic = "test_notification_topic"

[dependencies]
content_endpoint = "localhost:8080"