# Config file for local development.
# Feel free to push changes as long as
# they can be used by any developer
# and are reviewed by at least one
# codeowner.

[storage]
db_driver = "postgres"
pg_username = "postgres"
pg_password = "postgres"
pg_host = "localhost"
pg_port = 5432
pg_db_name = "notification"
pg_params = "sslmode=disable"
log_sql_queries = true

[logging]
debug = true
log_level = ""
