title: CCX Notification Service
description: CCX Notification Service
baseurl: /ccx-notification-service
url: "https://redhatinsights.github.io"
repository: "RedHatInsights/ccx-notification-service"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/ccx-notification-service"

footer_content: "Copyright &copy; 2021, 2022 Red Hat, Inc.</a>"

# Build settings
# markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - sources.tmpl.md
